const data = [
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },
    {
        img:"./public/images/shrek.jpg",
        title:"tytuł",
        rating:"5"
    },

]
export default data;
